config/routes.rb
Rails.application.routes.draw do
  root to: "homes#top"
  resources :trumps,only:[:create,:index]
  delete 'trumps' => 'trumps#destroy'
  post 'player' => 'player#create'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/player.rb
class Player < ApplicationRecord
  
end

app/models/suit.rb
class Suit < ApplicationRecord
end

app/models/trump.rb
class Trump < ApplicationRecord
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
    @cards = Trump.all
  end
end

app/controllers/p_controller.rb
class PController < ApplicationController
end

app/controllers/player_controller.rb
class PlayerController < ApplicationController
  def create
    @player = Player.new
    @player.save
  end
end

app/controllers/trumps_controller.rb
class TrumpsController < ApplicationController
  def create
    @trump = Trump.new
    if(rand(53) == 0)
      @trump.number = 0
      @trump.suit = 4
    else
      @trump.number = rand(13)+1
      @trump.suit = rand(4)
    end
    @trump.save
    
  end

  def index
    @players = Player.all
  end
  

  def edit
  end

  def update
  end

  def destroy
    Trump.destroy_all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/p_helper.rb
module PHelper
end

app/helpers/player_helper.rb
module PlayerHelper
end

app/helpers/trumps_helper.rb
module TrumpsHelper
end

app/views/homes/top.html.erb
<div class="container">
  <h1>トランプ管理</h1>
  <br>
  <div class = "list">
    <%= render 'trumps/list', cards: @cards %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Card</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/player/create.js.erb
<h1>Player#create</h1>
<p>Find me in app/views/player/create.html.erb</p>

app/views/trumps/_list.html.erb
<%= link_to "カードを引く", trumps_path, class: "btn btn-outline-dark", method: :post, remote: true %>
<% cards.each do |card| %>
    <% if card.suit == 4 %>
        JOKER
    <% else %>
        <%= Suit.find(card.suit).name + card.number.to_s %>
    <% end %>
<% end %>
<br>
<%= form_with url: trumps_path, local: true, method: :get do |f| %>
    <%= f.select :suit, ["♠", "♦", "♥", "♣", "JOKER"] %>
    <%= link_to "好きなカードを引く", trumps_path, class: "btn btn-outline-dark", method: :post, remote: true %>
<% end %>
<br>
<%= link_to "リセット", trumps_path, class:"btn btn-outline-dark", method: :delete, remote: true %>

app/views/trumps/create.js.erb
$(".list").html("<%= j(render 'trumps/list', cards: Trump.all) %>");

app/views/trumps/destroy.js.erb
$(".list").html("<%= j(render 'trumps/list', cards: Trump.all) %>");

app/views/trumps/edit.html.erb
<h1>Trumps#edit</h1>
<p>Find me in app/views/trumps/edit.html.erb</p>

app/views/trumps/index.html.erb
<div class="container">
  <h1>トランプ管理</h1>
  <br>
  <%= @players.each do |player| %>
    
    <div class = "list">
      <%= render 'trumps/list', cards: Trump.where(player_id: player.id) %>
    </div>
  <% end %>
  <div class = "new_player">
    <%= link_to "＋",player_path, class: 'btn btn-outline-dark',method: :post, remote: true %>
  </div>
</div>

app/views/trumps/update.html.erb
<h1>Trumps#update</h1>
<p>Find me in app/views/trumps/update.html.erb</p>